### ISSUE TITLE
arm/arm64 build ? No mention anywhere, no help around that architecture, no words on the readme on that.

### ISSUE THREAD

**Issue by tr1p0p** [YunoHost-Apps/retroarch_ynh#25]
Hi.

Yunohost is a well know for running a lots of greats apps and stuffs on Raspberry pi 3/4, the most selling computer on the world, so i was wondering, why this apps don't seem to take that in case ?

Because, despite the fact libretro/retroarch can be build for, literally, any architecture it's seem they're no arm64 build at all, so first question : why ?
And another one, why not a single mention on this architecture in the readme ? A common thing to do in yunohost readme, it would be great for the user that's are on arm64 architecture.

Thanks for the work still, hope this issues will be corrected

**Comment by Krakinou** [comment]
Hello,
As far as I'm aware, most of the magic of this retroarch implementation occurs in the browser itself, not on the server side.
So I don't think that arm/arm64 build is relevant as it's basically just a web page that is served to the client which does all the work locally.
However, I may be wrong, I just ported the [emscripten version](https://github.com/libretro/RetroArch/blob/master/pkg/emscripten/README.md) of retroarch without overanalyzed it, and there is not much documentation going around.

Finally : I'm not part at all of the retroarch project and just packaged it to yunohost for fun, so you may ask them directly the question [here](https://github.com/libretro/RetroArch/issues)

**Comment by tr1p0p** [comment]
(Wow, a peepoodoo PP)

Ok, i will look to the emiscripten version, but just to tell : the installation don't work on web admin and terminal way, so maybe missing somes packages for compilation ? Will look to that.

**Comment by Krakinou** [comment]
Quite strange as p7zip is part of the package dependencies.
Could you provide some log?
